[build]
builder = "DOCKERFILE"
dockerfilePath = "services/game-service/Dockerfile"
watchPatterns = ["packages/**", "services/game-service/**"]

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
